Update menu.ejs
TritonSE/uweast-ck pull request #42
Opened 2020-02-27 04:57 UTC by ganheather02

added storing info in JSON

Closes #29.

2020-02-28 06:08 UTC, NirmalAgnihotri submitted a review, later dismissed

2020-03-07 07:28 UTC, declansullivan commented on app/routes/menu/index.js
> +    res.cookie('cart', req.cookies.cart.push(req.body));
Remove this old line, this is what was giving us that `2` issue in the past

2020-03-07 07:29 UTC, declansullivan commented on app/views/menu.ejs
> +    <script type="text/javascript">
Remove this old code for cookies

2020-03-07 07:29 UTC, declansullivan requested changes
Remove old cookie code, as well as old line that gave us the list size error during the meeting

2020-03-10 18:25 UTC, declansullivan approved these changes
LGTM

2020-03-11 01:04 UTC, dhrvsood approved these changes

2020-03-11 01:04 UTC, merged