Update index.js
TritonSE/uweast-ck pull request #47
Opened 2020-04-20 06:12 UTC by ganheather02

added get and update methods

Closes #[ISSUE-NUM].

2020-04-20 06:18 UTC, reyna-abhyankar requested changes
Code isn't compiling - says items is not defined

2020-04-21 19:48 UTC, declansullivan requested changes
Adding the first item to the cart fails, this is because the TypeError we were getting in the past was when we were trying to push to undefined.  const { cart } = req.cookies does not cause an error, it only returns undefined, which causes problems down the road.  This should be a quick fix we can make and finalize by the end of the meeting

2020-04-21 19:48 UTC, declansullivan commented on app/routes/menu/index.js
>    } catch (TypeError) {
Need to change this to an if/else.

2020-04-28 02:32 UTC, declansullivan commented
Merged this PR into my post request PR

2020-04-28 02:32 UTC, closed without merging